module: device.settings
module_label: 设备设置
items:
  open_button:
    label: 设备设置按钮
    page: main
    automation_id: SetDeviceSetting
    control_type: Button
  dialog_marker:
    label: 设备设置标题
    page: main
    title: 设备设置
  device_type_combo:
    label: 设备类型下拉框
    page: dialog
    automation_id: DeviceTypes
    control_type: ComboBox
  sample_rate_combo:
    label: 采样率下拉框
    page: dialog
    automation_id: SampleRates
    control_type: ComboBox
  baud_rate_combo:
    label: 波特率下拉框
    page: dialog
    automation_id: BaudRates
    control_type: ComboBox
  head_box_number_combo:
    label: 头盒数目下拉框
    page: dialog
    automation_id: HeadBoxNumbers
    control_type: ComboBox
  ip_address_input:
    label: IP地址输入框
    aliases:
    - IP地址1输入框
    page: dialog
    automation_id: IPAddress1
    control_type: Edit
  ip_address_2_input:
    label: IP地址2输入框
    page: dialog
    automation_id: IPAddress2
    control_type: Edit
  port_input:
    label: 端口输入框
    page: dialog
    automation_id: Port
    control_type: TextBox
  device_name_input:
    label: 设备名称输入框
    page: dialog
    automation_id: BedNumber
    control_type: Edit
  gain_combo:
    label: 设备增益下拉框
    page: dialog
    automation_id: GainValues
    control_type: ComboBox
  confirm_button:
    label: 设备设置确认按钮
    page: dialog
    title: 确定
    control_type: Button
  close_button:
    label: 设备设置关闭按钮
    page: dialog
    title: 关闭
    control_type: Button
